### ISSUE TITLE
Connection failed

### ISSUE THREAD

**Issue by 15w34r0n3D4y** [Zexuz/Snack-Time#14]
Hey, can you help me with this err...

ConnectFailureException: Connection failed
ExtendedSocketException: No connection could be made because the target machine actively refused it 127.0.0.1:5672

Thank you.

**Comment by Zexuz** [comment]
I'm here to help.

I just need to more information. (Images is very helpful)

Where is this error coming from.
What ware you doing when this happened etc.

Without anymore information I can't help you

**Comment by 15w34r0n3D4y** [comment]
RabbitMQ.Client.Exceptions.BrokerUnreachableException
  HResult=0x80131620
  Message=None of the specified endpoints were reachable
  Source=RabbitMQ.Client
  StackTrace:
   at RabbitMQ.Client.ConnectionFactory.CreateConnection(IEndpointResolver endpointResolver, String clientProvidedName)
   at MediaHelper.MediaPlayerObserver.Program.StartAndSetupEventSystem(MPCHomeCinema mpcClient)
   at MediaHelper.MediaPlayerObserver.Program.<Main>d__2.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MediaHelper.MediaPlayerObserver.Program.<Main>(String[] args)

Inner Exception 1:
AggregateException: One or more errors occurred.

Inner Exception 2:
ConnectFailureException: Connection failed

Inner Exception 3:
ExtendedSocketException: No connection could be made because the target machine actively refused it 127.0.0.1:5672

![screenshoot](https://user-images.githubusercontent.com/13278733/49174740-4cb5a380-f347-11e8-83bd-1020b7b41bd7.png)

**Comment by Zexuz** [comment]
Have you installed RabbitMQ on your machine?

ATM RabbitMQ is a dependency, it will get removed in the future, but it's probably far away :/

**Comment by 15w34r0n3D4y** [comment]
I installed RabbitMQ Server and still got error (still refused), need check RabbitMQ first. Thank you.

**Comment by Zexuz** [comment]
Check that RabbitMQ is running. If that does not work, I can't really help. I will try and redo the code base some time, hopefully soon, so that RabbitMQ is no longer required.
